name: 'jacoco-badge-generator'
description: 'Github action for generating a jacoco coverage percentage badge.'
branding: 
  icon: 'book-open'
  color: 'green'
inputs:
  jacoco-csv-file:  
    description: 'Full path, relative to the root of the repository, to the jacoco csv file, including filename'
    required: false
    default: 'target/site/jacoco/jacoco.csv'
  jacoco-badge-file:
    description: 'Full path, relative to the root of the repository, to the created badge, including filename'
    required: false
    default: '.github/badges/jacoco.svg'
outputs:
  coverage:
    description: 'The jacoco coverage percentage as computed from the data in the jacoco.csv file.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jacoco-csv-file }}
    - ${{ inputs.jacoco-badge-file }}
